# Generated by Django 6.0.3 on 2026-03-17 08:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('current_location_lat', models.FloatField(default=0.0)),
                ('current_location_lon', models.FloatField(default=0.0)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_location_lat', models.FloatField(default=0.0)),
                ('pickup_location_lon', models.FloatField(default=0.0)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_location_lat', models.FloatField(default=0.0)),
                ('dropoff_location_lon', models.FloatField(default=0.0)),
                ('current_cycle_used', models.FloatField(help_text='Hours already used in the current 8-day cycle (0–70)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPUTING', 'Computing'), ('COMPUTED', 'Computed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('leg1_miles', models.FloatField(default=0.0)),
                ('leg2_miles', models.FloatField(default=0.0)),
                ('leg1_duration_hours', models.FloatField(default=0.0)),
                ('leg2_duration_hours', models.FloatField(default=0.0)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('daily_logs', models.JSONField(blank=True, default=list)),
                ('total_on_duty_hours', models.FloatField(default=0.0)),
                ('total_drive_hours', models.FloatField(default=0.0)),
                ('hos_compliant', models.BooleanField(default=False)),
                ('weekly_hours_used', models.FloatField(default=0.0)),
                ('weekly_hours_remaining', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
