# Generated by Django 6.0.3 on 2026-03-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
